Added the presumably last changes to this branch

diff --git a/linkall b/linkall
--- a/linkall
+++ b/linkall
@@ -9,23 +9,24 @@ reset="\e[39;49m"
 # Who am I?
 me=`basename $0`
 
+# PMD: The below code dosn't work yet
 # Get options.
-LNOPTS=""
-if [ $# -gt 0 ]; then
-  if [[ "$1" == "-f" ]]; then
-    LNOPTS="-f"
-  else
-    echo "Unrecognized option: $1"
-    cat << EOF
-Usage: $me [OPTIONS]
+# LNOPTS=""
+# if [ $# -gt 0 ]; then
+#   if [[ "$1" == "-f" ]]; then
+#     LNOPTS="-f"
+#   else
+#     echo "Unrecognized option: $1"
+#     cat << EOF
+# Usage: $me [OPTIONS]
 
-    Options:
-    -f    Force 'ln' to create a new link, even if one already exists with the
-          same name.
-EOF
-    exit 1
-  fi
-fi
+#     Options:
+#     -f    Force 'ln' to create a new link, even if one already exists with the
+#           same name.
+# EOF
+#     exit 1
+#   fi
+# fi
 
 # The system name is used to link platform-specific files.
 platform=`uname`
@@ -45,37 +46,39 @@ echo "Creating symlinks for all configuration files in $SCRIPTPATH."
 echo ""
 
 for dotfile in `find $SCRIPTPATH -mindepth 1 -maxdepth 1`; do
-  if [[ "${dotfile##*/}" == "bashrc" ]]; then
-    linkfile=".bash_profile"
-  else
-    # If the dotfile starts with an underscore-braced string, only link it if
-    # that string matches our platform.
-    if [[ "${dotfile##*/}" =~ "_.*_" ]]; then
-      if [[ "${dotfile##*/}" =~ "_${platform}_" ]]; then
-        linkfile=".${dotfile##*/_${platform}_}"
-      else
-        continue
-      fi
+    echo $dotfile
+    if [[ "${dotfile##*/}" == "bashrc" ]]; then
+        linkfile=".bash_profile"
     else
-      # This is the common case. Link the base name.
-      linkfile=".${dotfile##*/}"
+        # If the dotfile starts with an underscore-braced string, only link it if
+        # that string matches our platform.
+        if [[ "${dotfile##*/}" =~ "_.*_" ]]; then
+            if [[ "${dotfile##*/}" =~ "_${platform}_" ]]; then
+                linkfile=".${dotfile##*/_${platform}_}"
+            else
+                continue
+            fi
+        else
+            # This is the common case. Link the base name.
+            linkfile=".${dotfile##*/}"
+        fi
     fi
-  fi
-
-  if [ -d "./$linkfile" ]
-
-  if [ -e "$linkfile" ]; then
-    echo -n "${yellow}Exists${reset}"
-  else
-    ln -s $LNOPTS "$dotfile" "./$linkfile" > /dev/null 2>&1
-
-    if [ $? -eq 0 ]; then
-      echo -n "${green}OK${reset}    "
-    else
-      echo -n "${red}Failed${reset}"
-    fi
-  fi
-  echo " $dotfile -> $linkfile... "
+    echo "link file: $linkfile"
+    
+    if [ -d "./$linkfile" ]
+       
+       #if [ -e "$linkfile" ]; then
+       #    echo -n "${yellow}Exists${reset}"
+       #else
+           ln -s -f "$dotfile" "./$linkfile" > /dev/null 2>&1
+           
+           if [ $? -eq 0 ]; then
+               echo -n "${green}OK${reset}    "
+           else
+               echo -n "${red}Failed${reset}"
+           fi
+       #fi
+       echo " $dotfile -> $linkfile... "
 done
 
 if [ ! -d "$HOME/bin" ]; then
